<div class = 'content'>

<h2 class='highlight'>Agreement Between User and Star One Culture Ltd.</h2>
<p><span class = 'highlight'>This Agreement:</span> This Web Site Access and Use Agreement (the "Agreement") is between you and Star One Culture Ltd  ("Star One"), and contains terms and conditions pertaining to your use of the <a href='http://www.doralivehk.com' target='_blank'>www.doralivehk.com</a> (“DoraLiveHK”) web site. This Website is offered to you conditioned upon your acceptance without modification of the terms, conditions, and notices contained herein. Your use of the DoraLiveHK constitutes your agreement to all such terms, conditions, and notices. <b>If you do not agree to these terms and conditions, do not access or use the web site.</b></p>
		
<p><span class = 'highlight'>Modifications Of This Agreement:</span> Star One Culture Ltd reserves the right to change the terms, conditions, and notices under which the Website is offered, including but not limited to the charges (if any) associated with the use of the DoraLiveHK website. Notification of changes will be posted on the respective DoraLiveHK Website, and you are responsible for regularly reviewing these terms and conditions.</p>	

<h2 class='highlight'>Access and Limitations of Use</h2>
<p><span class='highlight'>Grant of Access:</span> This Agreement provides you with a non-exclusive grant of access to and use of the DoraLiveHK at the sole discretion of Star One Culture Ltd and subject to your continuing compliance with the terms and conditions of this Agreement.</p>
<p><span class='highlight'>Right To Restrict Access:</span> Star One Culture Ltd reserves the right to change, suspend, or discontinue any aspect of its any or all of DoraLiveHK at any time, including the availability of any feature, database or content contained in the Star One Culture Ltd Website. Star One Culture Ltd may also impose limits on certain features and services or restrict your access to parts of or all of DoraLiveHK without notice or liability. Star One Culture Ltd reserves the right in its sole discretion to correct any errors or omissions in any part of the Web Site.</p>

<p><span class='highlight'>Personal And Non-Commercial Use Limitation:</span> Unless otherwise specified, DoraLiveHK is for your personal and non-commercial use. You may not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any content, information, software, products or services obtained from this Star One Culture Ltd Website.</p>

<p><span class='highlight'>Links To Third Party Sites: </span>DoraLiveHK may contain links to other websites ("Linked Sites"). The Linked Sites are not under the control of Star One Culture Ltd and Star One Culture Ltd is not responsible for the contents of any Linked Site, including without limitation any link contained in a Linked Site, or any changes or updates to a Linked Site. Star One Culture Ltd is not responsible for webcasting or any other form of transmission received from any Linked Site. Star One Culture Ltd is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by Star One Culture Ltd of the Linked Site, its contents, or any association with its operators. Your use of any Linked Site is subject to the terms and conditions of the respective Linked Site.</p>

<p><span class='highlight'>No Unlawful Or Prohibited Use:</span> As a condition of your use of this Star One Culture Ltd Website, you warrant to Star One Culture Ltd that you will not use any Star One Culture Ltd Website for any purpose that is unlawful or prohibited by these terms, conditions, and notices. You may not use the Star One Culture Ltd Website in any manner which could damage, disable, overburden, or impair the Star One Culture Ltd Website or interfere with any other party's use and enjoyment of the Star One Culture Ltd Website. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available or provided for through the Star One Culture Ltd Website.</p>

<h2 class='highlight'>Intellectual Property</h2>
<p><span class='highlight'>Copyright: </span>All content of the DoraLiveHK is the copyrighted property of either Star One Culture Ltd and/or Star One Culture Ltd's participating partners and/or those providing content to Star One Culture Ltd ("Content Suppliers"). Trademarks: "Star One Culture Ltd" is the exclusive tradename of Star One Culture Ltd and other company names contained in the DoraLiveHK are the trademarks of their respective owners. Reservation of Rights: All copyrights, trademarks, and other intellectual property rights are hereby reserved.</p>

<h2 class='highlight'>Communication Services and Materials Provided by You:</h2>
<p><span class='highlight'>Use of Communication Services:</span> DoraLiveHK may contain news groups, forums, communities, calendars, and/or other message or communication facilities designed to enable you to communicate with the public at large or with a group (collectively, "Communication Services"). You agree to use the Communication Services only to post, send and receive messages and material that are proper and related to the particular Communication Service. By way of example, and not as a limitation, you agree that when using a Communication Service, you will not:</p>

<p>i.	Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others.
ii.	Publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful topic, name, material or information.
</p>

<p>iii.	Upload files that contain software or other material protected by intellectual property laws (or by rights of privacy of publicity) unless you own or control the rights thereto or have received all necessary consents. Upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another's computer.</p>

<p>iv.	Advertise or offer to sell or buy any goods or services for any business purpose, unless such Communication Service specifically allows such messages.</p>

<p>v.	Conduct or forward surveys, contests, pyramid schemes or chain letters.</p>
<p>vi.	Download any file posted by another user of a Communication Service that you know, or reasonably should know, cannot be legally distributed in such manner.</p>

<p>vii.	Falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded.</p>
<p>viii.	Restrict or inhibit any other user from using and enjoying the Communication Services.</p>
<p>ix.	Violate any code of conduct or other guidelines which may be applicable for any particular Communication Service or violate any applicable laws or regulations.</p>
<p>x.	Harvest or otherwise collect information about others, including e-mail addresses, without their consent.</p>

<p><span class='highlight'>No Obligation To Monitor Communication Services:</span> Star One Culture Ltd has no obligation to monitor the Communication Services. However, Star One Culture Ltd reserves the right to review materials posted to a Communication Service and to remove any materials in its sole discretion. Star One Culture Ltd also reserves the right in its sole discretion to terminate your access to any or all of the Communication Services at any time without notice for any reason whatsoever.</p>

<p><span class='highlight'>Limitation of Liability:</span> Always use caution when giving out any personally identifying information about yourself or your children in any Communication Service. Star One Culture Ltd does not control or endorse the content, messages or information found in any Communication Service and, therefore, Star One Culture Ltd specifically disclaims any liability with regard to the Communication Services and any actions resulting from your participation in any Communication Service. Materials uploaded to a Communication Service may be subject to posted limitations on usage, reproduction and/or dissemination, you are responsible for adhering to such limitations if you download the materials.</p>

<p><span class='highlight'>Right To Disclose Information Under Certain Circumstances:</span> Star One Culture Ltd reserves the right at all times to disclose any information as necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in Star One Culture Ltd's sole discretion. Please refer to our Privacy Policy regarding our collection and use of your personally identifiable information.</p>

<p><span class='highlight'>Submissions Provided By You Not Confidential:</span> You acknowledge that any materials or messages posted, files uploaded, data input or any other form of communication through DoraLiveHK("Submissions") are not confidential and that such Submissions may be read or intercepted by others. You acknowledge that by submitting Submissions to  DoraLiveHK no confidential, fiduciary, contractually implied or other relationship is created between you and Star One Culture Ltd other than pursuant to this Agreement.</p>

<p><span class='highlight'>License To Star One Culture Ltd In Submissions: </span>By posting, uploading, inputting, providing or submitting your Submission you are granting Star One Culture Ltd, its affiliated companies and sublicensees the non-exclusive worldwide unrestricted cost and royalty-free license to copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate and reformat your Submission; and to publish your name in connection with your Submission, in connection with commercial or non-commercial endeavours. No compensation will be paid with respect to such use of your Submission. Star One Culture Ltd is under no obligation to post or use any Submission you may provide and Star One Culture Ltd may remove any Submission at any time in Star One Culture Ltd's sole discretion.</p>

<p><span class='highlight'>Warranty & Representation:</span> By posting, uploading, inputting, providing or submitting your Submission you warrant and represent that you own or otherwise control all of the rights to your Submission as described in this section including, without limitation, all the rights necessary for you to provide, post, upload, input or submit the Submissions and to grant to Star One Culture Ltd the right and license to copy, publicly display and otherwise exploit your Submission as more fully described in the preceding paragraph. You hereby waive all rights to any claim against Star One Culture Ltd for any alleged or actual infringements of any proprietary rights, rights of privacy and publicity, moral rights and rights of attribution in connection with such Submissions.</p>

<h2 class='highlight'>Software Available on the Web Site</h2>

<p><span class='highlight'>Software License Agreement:</span> Your use of software (if any) that is made available to download from this Star One Culture Ltd Website, excluding software that may be made available by end-users through a Communication Service ("Software"), is governed by the terms of the end user license agreement, if any, which accompanies or is included with the Software ("License Agreement"). You may not install or use any Software that is accompanied by or includes a License Agreement unless you first agree to the License Agreement terms. For any Software not accompanied by a License Agreement, Star One Culture Ltd hereby grants to you, the user, a personal, non-transferable license to use the Software only for viewing and otherwise using the Web Site in accordance with the terms of this Agreement, and for no other purpose. All Software Copyright Protected. All Software is the copyrighted work of Star One Culture Ltd and/or its Content Suppliers and is protected by copyright laws and international treaty provisions, all of which being hereby reserved. Any reproduction or redistribution of the Software is expressly prohibited by law, and may result in severe civil and criminal penalties. Violators will be prosecuted to the maximum extent possible. You shall keep intact all copyright and other proprietary notices. Without limiting the foregoing, copying or reproduction of the software to any other server or location for further reproduction or redistribution is expressly prohibited. the software is warranted, if at all, only according to the terms of the License Agreement. You acknowledge that the Software, and any accompanying documentation and/or technical information, is subject to applicable export control laws and regulations of Hong Kong. You agree not to export or re-export the Software, directly or indirectly, to any countries that are subject to these export restrictions.</p>

<h2 class = 'highlight'>Liability Disclaimers and Limitations</h2>

<p><span class='highlight'>No Representation or Warranties by Star One Culture Ltd:</span> You agree that this Star One Culture Ltd Web Site, including all content, Software, functions, materials and information made available on or accessed through the Star One Culture Ltd Websites, are provided to you at your own risk for your personal non-commercial use and on an "as is, as available" basis. To the fullest extent permissible by law, Star One Culture Ltd makes no representations, endorsements or warranties, expressed or implied, including, but not limited to, those of merchantability or fitness for a particular purpose, with respect to Star One Culture Ltd, the Web Site, or any content, merchandise, information or service provided through DoraLiveHK or on the Internet generally or the functions made accessible by any software used on or accessed through the Star One Culture Ltd Websites, for any hypertext links to third party web sites or for any breach of security associated with the transmission of sensitive information through the Web Site or any linked site. Star One Culture Ltd does not warrant that the functions contained in DoraLiveHK or any content contained therein will be uninterrupted, error free or that defects will be corrected. No Endorsement by Star One Culture Ltd of Internet information: You understand that Star One Culture Ltd or its Content Suppliers do not operate, control, or endorse any information, products or services on the internet in any way nor does Star One Culture Ltd or its Content Suppliers represent or endorse the accuracy or reliability of any advice, opinion, statement or other content displayed or distributed through the Web Site. You acknowledge that any reliance upon any such opinion, advice, statement, memorandum, or content shall be at your sole risk. You agree that neither Star One Culture Ltd nor its Content Suppliers shall be liable for any cost or damage arising either directly or indirectly from any such opinions, advice, services, merchandise and other content. You understand further that the internet contains unedited materials, some of which are sexually explicit or may be offensive to you, that you access such materials at your own risk and that Star One Culture Ltd has no control over and accepts no responsibility whatsoever for such materials.</p>

<p><span class='highlight'>No Liability:</span> You agree that in no event will Star One Culture Ltd, its affiliates, and Star One Culture Ltd's and its affiliates' respective officers, directors, employees, agents and contractors be liable for: (i) any incidental, consequential, or indirect damages (including, but not limited to, damages for loss of profits, business interruption, loss of programs or information, and the like) arising out of the use of or inability to use the Web Site, or any content or transactions provided on the Web Site, even if Star One Culture Ltd, its affiliates, and Star One Culture Ltd's and its affiliates or their authorized representatives have been advised of the possibility of such damages; or (ii) any claim attributable to errors, omissions, or other inaccuracies in  DoraLiveHK and/or content, materials or information downloaded through this Star One Culture Ltd Website; or (iii) any injury, sickness, disease, death, damages, claims, or liability arising out of or attributable to the use by anyone of DoraLiveHK or of any hardware, including any television set, monitor, or screen, arising out of or attributable to use by anyone of such hardware for the purpose of accessing and/or viewing this Star One Culture Ltd Website.</p>

<p><span class='highlight'>Indemnity:</span> You undertake and agree to ensure that all persons you authorize to use DoraLiveHK have read and will comply with the terms and conditions of this Agreement and are solely responsible and liable for actions which are in contravention of this Agreement or any applicable law. You agree to indemnify, defend and hold harmless Star One Culture Ltd, from and against all losses, expenses, damages and costs, including reasonable attorney's fees, resulting from any violation of this Agreement or any activity related to DoraLiveHK (including negligent or wrongful conduct) by you, by any persons allowed by you to access DoraLiveHK or by any other person accessing DoraLiveHK or services provided pursuant to DoraLiveHK using your identification or password. The provisions of this paragraph are for the benefit of Star One Culture Ltd, its affiliates, and their respective officers, directors, employees, agents and contractors. Each of these entities or individuals shall have the right to assert and enforce these provisions directly against you on its own behalf.</p>

<p>Star One Culture Ltd reserves the right (but has no obligation), at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you hereunder, and in such event, you shall have no further obligation to provide indemnification for such matter.</p>

<h2 class='highlight'>General</h2>
<p>
You agree that no joint venture, partnership, employment, or agency relationship exists between you and Star One Culture Ltd as a result of this Agreement or use of this Star One Culture Ltd Website. Star One Culture Ltd's performance of this Agreement is subject to existing laws and legal process, and nothing contained in this Agreement is in derogation of Star One Culture Ltd's right to comply with governmental, court and law enforcement requests or requirements relating to your use of DoraLiveHK or information provided to or gathered by Star One Culture Ltd with respect to such use. If any part of this Agreement is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of this Agreement shall continue in effect. Unless otherwise specified herein, this Agreement constitutes the entire agreement between the user and Star One Culture Ltd with respect to DoraLiveHK and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between the user and Star One Culture Ltd with respect to this Star One Culture Ltd Website. Headings are for convenience only. A printed version of this Agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this Agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. This Agreement and your use of DoraLiveHK shall be governed by the laws of Hong Kong applicable therein. You agree that exclusive jurisdiction for any claim or dispute resides in the courts of Hong Kong. You further agree and expressly consent to attorn to the jurisdiction of the courts of  Hong Kong in connection with any dispute or claim involving you, Star One Culture Ltd, Star One Culture Ltd's affiliates, or the Star One Culture Ltd Websites. Star One Culture Ltd may assign its rights under this Agreement and its ownership of the Web Site or any interest therein at any time without notice to you. You may not assign your rights under this Agreement to anyone.
</p>
</div>